trigger:
  batch: true
  branches:
    include:
    - '*'

jobs:
- job: 'Test'
  strategy:
    matrix:
      Python27Linux:
        imageName: 'ubuntu-18.04'
        python.version: '2.7'
      Python27Mac:
        imageName: 'macos-10.15'
        python.version: '2.7'
      Python36Linux:
        imageName: 'ubuntu-18.04'
        python.version: '3.6'
      Python36Mac:
        imageName: 'macos-10.15'
        python.version: '3.6'
      Python36Windows:
        imageName: 'windows-2019'
        python.version: '3.6'
      Python37Linux:
        imageName: 'ubuntu-18.04'
        python.version: '3.7'
      Python37Mac:
        imageName: 'macos-latest'
        python.version: '3.7'
      Python37Windows:
        imageName: 'windows-latest'
        python.version: '3.7'
      Python38Linux:
        imageName: 'ubuntu-latest'
        python.version: '3.8'
      Python38Mac:
        imageName: 'macos-latest'
        python.version: '3.8'
      Python38Windows:
        imageName: 'windows-latest'
        python.version: '3.8'
      Python39Linux:
        imageName: 'ubuntu-latest'
        python.version: '3.9'
      Python39Mac:
        imageName: 'macos-latest'
        python.version: '3.9'
      Python39Windows:
        imageName: 'windows-latest'
        python.version: '3.9'
      Python310Linux:
        imageName: 'ubuntu-latest'
        python.version: '3.10'
      Python310Mac:
        imageName: 'macos-latest'
        python.version: '3.10'
      Python310Windows:
        imageName: 'windows-latest'
        python.version: '3.10'
    maxParallel: 4
  pool:
    vmImage: $(imageName)

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: choco install llvm
    condition: eq( variables['Agent.OS'], 'Windows_NT')
    displayName: 'Preinstall (Windows)'

  - script: |
      python -m pip install --upgrade pip wheel setuptools
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  # Set the correct paths and includes. Only the env variables set here are
  # used, not the ones defined in the .jsonl.
  - script: |
      set "PATH=C:\Program Files\LLVM\bin;%PATH%"
      set "INCLUDE=%$VC_INCLUDEPATH%"
      clang --version
      python setup.py bdist_wheel
    condition: eq( variables['Agent.OS'], 'Windows_NT')
    displayName: 'Build wheel (Windows)'

  - script: python setup.py bdist_wheel
    condition: eq(variables['Agent.OS'], 'Darwin')
    displayName: 'Build wheel (Mac)'

  - script: |
      gcc --version
      python setup.py bdist_wheel
    condition: and(eq(variables['Agent.OS'], 'Linux'), or(eq(variables['python.version'], '2.7'), eq(variables['python.version'], '3.5')))
    displayName: 'Build wheel (Linux)'

  - script: |
      clang --version
      CC=clang python setup.py bdist_wheel
    condition: and(eq(variables['Agent.OS'], 'Linux'), eq(variables['python.version'], '3.6'))
    displayName: 'Build wheel (Linux / clang)'

  - script: |
      gcc-7 --version
      CC=gcc-7 python setup.py bdist_wheel
    condition: and(eq(variables['Agent.OS'], 'Linux'), eq(variables['python.version'], '3.7'))
    displayName: 'Build wheel (Linux / gcc-7)'

  - script: |
      gcc-9 --version
      CC=gcc-9 python setup.py bdist_wheel
    condition: and(eq(variables['Agent.OS'], 'Linux'), eq(variables['python.version'], '3.8'))
    displayName: 'Build wheel (Linux / gcc-9)'

  - script: |
      gcc-10 --version
      CC=gcc-10 python setup.py bdist_wheel
    condition: and(eq(variables['Agent.OS'], 'Linux'), eq(variables['python.version'], '3.9'))
    displayName: 'Build wheel (Linux / gcc-10)'

  - script: |
      clang-12 --version
      CC=clang-12 python setup.py bdist_wheel
    condition: and(eq(variables['Agent.OS'], 'Linux'), eq(variables['python.version'], '3.10'))
    displayName: 'Build wheel (Linux / clang-12)'

  - task: PythonScript@0
    inputs:
      scriptSource: inline
      script: |
        # https://github.com/pypa/pip/issues/6951
        import os
        wheel_file = os.listdir('./dist')[0]
        wheel_path = os.path.join('./dist', wheel_file)
        os.rename(wheel_path, wheel_path.replace("cp38m-win", "cp38-win"))
        print(os.listdir('./dist'))
      failOnStderr: true
    condition: and(eq(variables['Agent.OS'], 'Windows_NT'), eq(variables['python.version'], '3.8'))
    displayName: Fix wheel name (Windows, Python 3.8)

  - script: |
      pip freeze > installed.txt
      pip uninstall -y -r installed.txt
    displayName: 'Uninstall all packages'

  - bash: |
      rm -rf blis*
      python -m pip install dist/*.whl
    displayName: 'Install wheel'

  - script: |
      pip install -r requirements.txt
      python -m pytest --pyargs blis
    displayName: 'Run tests'
